name: Selkie
on:
  workflow_call:
    secrets:
      docker-hub-user:
        description: 'Docker hub user'
        required: false
      docker-hub-secret:
        description: 'Docker hub secret'
        required: false
    inputs:
      artifact-name: # id of input
        description: 'artifact name'
        required: true
        type: string
      artifact-repo: # id of input
        description: 'artifact name'
        required: true
        type: string
      artifact-version: # id of input
        description: 'artifact name'
        required: true
        type: string
      push_docker:
        description: "Push docker image to registry"
        required: false
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'

    - name: Set image name
      run: |
        echo "artifact_image_name=docker.io/${{ inputs.artifact-repo }}/${{ inputs.artifact-name }}:${{ inputs.artifact-version }}" >> $GITHUB_ENV

    - name: Build image
      run: |
        ./mvnw -B spring-boot:build-image -Dspring-boot.build-image.imageName=${{ env.artifact_image_name }}

    - name: Login to Docker Hub
      if: inputs.push_docker
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.docker-hub-user }}
        password: ${{ secrets.docker-hub-secret }}

    - name: Push Docker image
      if: inputs.push_docker
      run: |
        docker push ${{ env.artifact_image_name }}
