name: Selkie push

on: push

jobs:
  build-image:
    uses: ./.github/workflows/build-docker-image.yml
    permissions:
      contents: read
      packages: write
    with:
      artifact-name: selkie
      artifact-repo: josefilipeii
      artifact-version: ${{github.sha}}
      push_docker: false
    secrets:
      docker-hub-user: ${{ secrets.DOCKERHUB_USERNAME }}
      docker-hub-secret: ${{ secrets.DOCKERHUB_PASSWORD }}
